### ISSUE TITLE
A Few Issues

### ISSUE THREAD

**Issue by lordegeorge** [crashtheparty/EnchantmentSolution#10]
We've had some problems using this plugin, and for simplicity, I'll just list them here:

- _Shocking Aspect - The lightning allows players to kill other players and mobs in areas where they shouldn't be able to_ **(Moved to #11)**
- _Warp - one hit, even in areas where PvP is disabled TP's you to other places (like places where PvP is enabled) and gets activated every hit so the end result is people TPing everywhere_ **(Moved to #12)**
- Anvil - if the anvil is about to break and you're combining some items, the item you combine will disappear
- _Smeltery - interferes with GriefPrevention_ **(Moved to #13)**

We did try disabling these in the config, but that only disables them from being enchanted and not from working on already enchanted items.

**Comment by crashtheparty** [comment]
1. Which items were being combined in the Anvil? I have never seen an issue with this.

2. You can remove all of the disabled enchantments from items by using the "disable_enchant_method" set to "vanish".

**Comment by lordegeorge** [comment]
Oh, just now seeing it (github never sent me an email notification?) Thanks so much for the response and sorry for my slow response...

I'll try the configuration option and I will see about which items were being combined, although I think it was anything.
Thanks again.

**Comment by lordegeorge** [comment]
Apparently, the anvil issue was only reported once, so it may have just been an issue with the individual rather than with the plugin. Thanks for all your help :)
