### ISSUE TITLE
Cannot Trade Enchanted NBT items with Villagers

### ISSUE THREAD

**Issue by MadHub223** [crashtheparty/EnchantmentSolution#101]
**Describe the bug**
The bug is that when trying to trade an NBT enchanted item with a trader, it will not go through.

**Debug.yml**
https://pastebin.com/kGPKUyzP

**To Reproduce**
1. Create villager with ability to trade an enchanted item.
2. Give Villager the enchanted item
3. Trade preview completes
4. Cannot take out item.

**Expected behavior**
I expected the Villager to take the item and trade properly.

**Screenshots**
https://i.imgur.com/rdUju1p.png

**Additional context**
The commands I used are available here: https://pastebin.com/XQPfMqqG

**Comment by crashtheparty** [comment]
Able to replicate on a clean spigot server; this is a spigot bug, not an enchantment solution bug.
