### ISSUE TITLE
Irene's Lasso Not Working

### ISSUE THREAD

**Issue by SomeDumbNinja** [crashtheparty/EnchantmentSolution#102]
**Bug:**
On the wiki it says right-clicking a block will release the animal captured by Irene's Lasso but nothing seems to happen at all.

I don't have access to the debug file.

**How to Reproduce:**
1. Get Irene's Lasso
2. Capture an animal (I captured a cow)
3. Release the animal
4. Doesn't release at all

**Comment by crashtheparty** [comment]
Please send the debug.yml file generated with /esdebug
