### ISSUE TITLE
Anvil combining costs far too low/reduced

### ISSUE THREAD

**Issue by NightScythe1** [crashtheparty/EnchantmentSolution#106]
**Describe the bug**
When combining items or adding enchantments to an item in an anvil, the cost will appear for a split-second before being 'corrected' to a far lower one, usually at just 1 xp level. It only begins to gradually increase after about 5 additions/combinations. I have all custom GUIs disabled but the same bug occurs using the /esanvil command.

**Debug.yml**

[https://pastebin.com/ZHEdzsRD](url)

**To Reproduce**
1. Gather many enchantment books like 'sharpness'
2. Enter the anvil and keep combining them to higher level
3. You should see for a good portion of early combinations the cost stays at 1

**Expected behavior**
It would've been expected that the costs would increase or scale as usual, increasing by a few levels each combination.

**Screenshots**
I have no screenshots, but i did record an example of the glitch.
[https://youtu.be/ANN_z35kR4g](url)

**Additional context**

**Comment by crashtheparty** [comment]
Not a bug; this is caused by the anvil.level_divisor in config.yml being set to 4 by default. Setting it to a lower number will stop it from happening (1 is the vanilla value).
