### ISSUE TITLE
Issue with Enchantment Solution

### ISSUE THREAD

**Issue by YTPmaster** [crashtheparty/EnchantmentSolution#113]
**Describe the bug**
Enchantments randomly duplicate in items description.

**Debug.yml**
https://pastebin.com/UfmgF17e

**To Reproduce**
1. Enchant Item with Custom Enchant
2. Use item normally. (kill mobs with swords, mine with pickaxe, ect)
3. Bug happens

**Expected behavior**
Enchant the item and have it appear once in item description

**Screenshots**
https://imgur.com/8WrwC0S
https://imgur.com/uIDSpZQ

**Additional context**
Seemingly happens at random points. I couldnt reproduce it on a wood sword, but could on a netherite sword.

**Comment by crashtheparty** [comment]
Please use a newer version.
