### ISSUE TITLE
Zeal and SplatterFest doesn't work on Survival mode

### ISSUE THREAD

**Issue by NekomataGami** [crashtheparty/EnchantmentSolution#123]
Describe the bug:
Zeal and SplatterFest enchantment for hoe doesn't shoot fireball/eggs when left clicked, works just fine on creative mode.

Debug.yml:
https://pastebin.com/iyKc7sY6

To Reproduce
  1. Go to a server
  2. Make sure you're on survival mode
  3. Enchant a hoe with zeal or splatterfest
  4. left click while holding the hoe

Expected behavior:
Its suppose to shoot fireball on zeal, eggs on splatter fest

**Comment by steven11304** [comment]
i have a same problem
