### ISSUE TITLE
Enchantment result differs from offering in enchanting table

### ISSUE THREAD

**Issue by Quantum001** [crashtheparty/EnchantmentSolution#134]
**Describe the bug**
Sometimes when you enchant and item, the table will indicate one enchantment and then when the player enchants, the enchantment is completely different.

**Debug.yml**
https://gist.github.com/Quantum001/bde98e8fc73f126779522c299985bf86

**To Reproduce**
Disabled the custom gui for the enchanting table in the config.
Attempt to enchant a number of tools, paying attention to the enchantment listed, and the enchantment provided.

**Expected behavior**
When the table indicates that the enchantment will be Efficiency IV, the resulting enchant should have at least Efficiency IV.

**Screenshots**
https://youtu.be/MfWVbLBJUDk

**Additional context**
N/A

**Comment by crashtheparty** [comment]
Unable to fix; this is an issue with Spigot not allowing for custom enchantments to be added into the enchanting table like vanilla enchantments.
