### ISSUE TITLE
Plugin doesnt load

### ISSUE THREAD

**Issue by Realhercules** [crashtheparty/EnchantmentSolution#18]
I put jar file into plugins folder and spigot 1.13.2 doesnt load it.
Is there ang easy Way to use it on 1.13.2?
Or it needs some special plugin to work?

**Comment by crashtheparty** [comment]
Please give more information for this. What does the console say? What other plugins are you using?

**Comment by Realhercules** [comment]
Console didnt say even word about it...
I downloaded "pre-release" version and that works fine :dancing_women:

**Comment by Realhercules** [comment]
Pre-release is working cool
