### ISSUE TITLE
Shift-clicking name tag into double chest causes Anvil GUI

### ISSUE THREAD

**Issue by dfsek** [crashtheparty/EnchantmentSolution#19]
When a player renames a Name Tag in an Anvil, then shift-clicks it into a double chest, the top half of the chest becomes a functional Anvil GUI. Then, when the chest is closed and reopened, the GUI items remain, but are not protected by the plugin, allowing players to take any items from it, including Barrier Blocks.

**Comment by crashtheparty** [comment]
Unable to reproduce. Please send a video showing the steps.

**Comment by dfsek** [comment]
[https://www.youtube.com/watch?v=W6M-q8BTJ6I](https://www.youtube.com/watch?v=W6M-q8BTJ6I)
Some things that may affect the outcome: 
- The chest must be a double chest. 
- The renamed name tag must be shift+left-clicked into the chest.
- My server is running [Paper Spigot](https://papermc.io/)

EDIT: The plugins on my server are `Arconix, AuthMe, ChatControl, Citizens, CT-Core, CustomEnderChest, DiscordSRV, dynmap, Dynmap-Essentials, dynmap-mobs, Dynmap-Towny, EnchantmentSolution, EpicFurnaces, Essentials, eZProtector, FastAsyncWorldEdit, Harbor, Highwayman, LiteBansGUI, LuckPerms, OpenInv, PlayerShopGUIPlus, PlugMan, ProtocolLib, Sentinel, ShopGUIPlus, SkinsRestorer, Statscraft, SuperVanish, TallNether, Towny, TownyChat, TownyNameUpdater, Vault, VeinMiner, WorldEdit, WorldGuard, WorldGuardExtraFlags`
