### ISSUE TITLE
Using items with attributes in an anvil is very buggy

### ISSUE THREAD

**Issue by danielroberts20** [crashtheparty/EnchantmentSolution#21]
Using EnchantmentSolution 1.4.5

When using 2 (or even just 1) item(s) with attributes in an anvil, they do not combine and a 3rd, visual-glitched item is produced but cannot be obtained.

See:

https://streamable.com/skz7x

**Comment by crashtheparty** [comment]
Are there any issues in the console that this is creating?

**Comment by crashtheparty** [comment]
Is this a critical bug for your server?

**Comment by danielroberts20** [comment]
The console is empty when I'm putting the items in the anvil and attempting to combine them.

This is a critical bug for my server as we heavily revolve around this type of gear.

**Comment by danielroberts20** [comment]
This issue is still persistent in 2.0.0.

I believe the functionality should be that the attributes of the first item (leftmost slot) should be carried over to the final item.

See here:

https://streamable.com/5csfv

**Comment by crashtheparty** [comment]
Please leave the issue that is happening in the console. I do not believe it's an attributes error any more, since it works fine for me.

**Comment by danielroberts20** [comment]
Sorry about this, I didn't even think twice to test by itself.

I believe the issue may lie with MythicMobs as that's the plugin I'm using to get these items with attributes.

Maybe this will help:

https://pastebin.com/KhNW6vCb

**Comment by crashtheparty** [comment]
That’s fine! Thought I fixed that issue too but apparently I didn’t. I’ll look into it later today and try again.

**Comment by danielroberts20** [comment]
Thank you! Really appreciate the work you put into maintaining this plugin.

Love 2.0.0 by the way :)

**Comment by crashtheparty** [comment]
Newest version should fix the issue, but I also added some extra debugging just to check for what exactly is causing issues. If you are able to try to combine items with custom attributes and send anything that happens in the console, that would be appreciated.

**Comment by danielroberts20** [comment]
Trying to combine 2 axes with the attack speed attribute and the attack damage attribute:

https://pastebin.com/F2pVKcze

Gives this:

https://imgur.com/a/s6s0WXn
-------------------------------------------------------------------------------------------------------------------
Trying to combine 2 helmets with Health, Luck, Armor Toughness, Armor and Knockback resistance attributes:

https://pastebin.com/iWTzbGWZ

Gives this:

https://imgur.com/a/KaQFkeA

**Comment by danielroberts20** [comment]
Definitely an improvement as they are actually combining now though

**Comment by crashtheparty** [comment]
Added a new 2.0.2 version for you.

In addAttributeModifier under ItemMeta, I found this line of code:

* Two {@link AttributeModifier}s that have the same {@link java.util.UUID} cannot exist on the same Attribute.

Whereas in the error log:

06.05 17:56:58 [Server] WARN [EnchantmentSolution] Issue with adding GENERIC_KNOCKBACK_RESISTANCE with modifier AttributeModifier{**uuid=6735fce8-7783-f5a4-9a51-3977373132a1**, name=generic.knockbackResistance, operation=ADD_NUMBER, amount=5.645639682647378, slot=HEAD} to item.
06.05 17:56:58 [Server] WARN [EnchantmentSolution] Possible conflict: GENERIC_ARMOR_TOUGHNESS with modifier AttributeModifier{**uuid=6735fce8-7783-f5a4-9a51-3977373132a1**, name=generic.armorToughness, operation=ADD_NUMBER, amount=2.8886244637760172, slot=HEAD}.

The UUIDs are exactly the same for some reason, so even though they exist on the same item before, they have an issue going to the new item.

**Comment by danielroberts20** [comment]
Thank you so much!

<3
