### ISSUE TITLE
Level 50 Enchantments cannot be enabled

### ISSUE THREAD

**Issue by activitytimer** [crashtheparty/EnchantmentSolution#24]
I recently updated my server to 1.14 and am running 2.0.1, and in the config.yml file, I have "level_50_enchants" set to true. However, in-game, when a player opens an enchantment table, it says that level 50 enchants are disabled.

I have looked through the config files and don't see anything that may be causing this, am I missing something?

**Comment by crashtheparty** [comment]
1. Did you use Enchantment Solution 1.4.5 or lower?
2. Are there any issues in the console?
3. Please send your config.yml, enchantments.yml, and enchantments_advanced.yml files

**Comment by activitytimer** [comment]
I am using 2.0.1
No, no issues in the console
[config.yml](https://pastebin.com/RpbuJPbB)
[enchantments.yml](https://pastebin.com/6nvEMTeX)
[enchantments_advanced.yml](https://pastebin.com/eijUEFG1)

**Comment by activitytimer** [comment]
wow, I am very stupid sometimes
I forgot to surround the table with books!
Sorry for wasting your time :/
