### ISSUE TITLE
Illegal Argument Exception when processing Attributes

### ISSUE THREAD

**Issue by danielroberts20** [crashtheparty/EnchantmentSolution#26]
I'm trying to combine items with 2 attributes and there appears to be a problem with adding item 1's attributes to the new item's attributes.

https://pastebin.com/zFuq2HDc

Spigot 1.13.2
EnchantmentSolution 2.0.3
EnchantmentSolutionAdditions 1.0.1

**Comment by crashtheparty** [comment]
Can you send a screenshot of the items with both their attributes?

**Comment by danielroberts20** [comment]
https://streamable.com/nqnf0

**Comment by crashtheparty** [comment]
Do you have a discord? I want to send debug versions over to you without having to release several new versions, as all I can do at this point is guess at what the bug is.

**Comment by danielroberts20** [comment]
Dan Roberts#3756
