### ISSUE TITLE
Lets say random weird issus

### ISSUE THREAD

**Issue by dryter97** [crashtheparty/EnchantmentSolution#28]
there is a stacktrace of the issus on an internal server

[https://i.qcfb.ca/20190624221708.png](https://i.qcfb.ca/20190624221708.png)

due to an unsafe enchantement tank 12 on a axe i did for a test for a mythic mobs compatibility axe. so the axe is this one:

![2019-06-24_22 21 53](https://user-images.githubusercontent.com/16638986/60064474-8b89bd00-96ce-11e9-9074-0806f705a400.png)

nothing else to explain. i know tank is not there to be on a axe. it was just for a simple enchantement test.

**Comment by crashtheparty** [comment]
Found the bug and fixed it! It was an issue with enchantments higher than level 10 and has been in since 1.0.0.

Secondly, have you used EnchantmentSolution on a version lower than 1.13? If not, "update_legacy_enchantments" should be set to false, not true.
