### ISSUE TITLE
Conflicting enchantments not being respected Vol. 2

### ISSUE THREAD

**Issue by PsychoLynx** [crashtheparty/EnchantmentSolution#31]
As per #27, except this time it's armor, where players can receive e.g. Fire Protection, Projectile Protection AND Protection in the same diamond chestplate.

**Comment by crashtheparty** [comment]
Try checking "protection_conflicts" in config.yml. If that's false, it should be true.

**Comment by PsychoLynx** [comment]
I just checked. It is true.

Config: https://pastebin.com/QARKyEWy
Enchantments_advanced: https://pastebin.com/MVJngTCF

**Comment by PsychoLynx** [comment]
Come to think of it, looks like I am missing the conflicting enchantments from enchantments advanced. I'll try adding them.

**Comment by PsychoLynx** [comment]
Yeah, that was totally my own damn fault for not checking the configs carefully enough. Sorry!
