### ISSUE TITLE
enchant splatter fest just not working

### ISSUE THREAD

**Issue by dryter97** [crashtheparty/EnchantmentSolution#35]
enchant splatter fest just not working nothing about error in console just saw its not working.... so i just gess the enchant is not casted at all player can got the enchant but not shooting eggs has intended. paper 1.14.4 latest atm

**Comment by dryter97** [comment]
2.1.4 version of enchantmentsolution. not a big deal i think maybe just a forgot

**Comment by crashtheparty** [comment]
Works as intended for me. Do you have eggs in your inventory?

**Comment by dryter97** [comment]
mmmm i thought it was not needed? whats the purpose for if we need eggs to
throw eggs xd
hoe are not use btw for pvp so

Le mar. 30 juil. 2019 à 14:51, crashtheparty <notifications@github.com> a
écrit :
