### ISSUE TITLE
Permission to use higher level books on anvil

### ISSUE THREAD

**Issue by PsychoLynx** [crashtheparty/EnchantmentSolution#36]
Hi, it's me again!

The players on my server are in a habit of enchanting books a lot. However, currently when the they receive enchantments out of the normal range (e.g. Unbreaking 5) on a book and attempt to add it to an item on an anvil, the item only receives Unbreaking 3 (due to not allowing enchantment combining over natural levels in my config). 

Would it be possible to add an exception permission for enchanted books?

Thank you again for this wonderful plugin.

**Comment by crashtheparty** [comment]
Yes, I can probably add that to the demigod-anvil permission. Not sure if I updated that on the resource page but it’s in the change logs. I’m away for the week but once I’m back I’ll add it!

**Comment by PsychoLynx** [comment]
Thank you, although I would maybe suggest making it a separate permission for those people who want to fine-tune the permissions. Thanks again and hope you have a nice time while away!
