### ISSUE TITLE
Enchantments are changing when I travel to other worlds.

### ISSUE THREAD

**Issue by DragonisOmega** [crashtheparty/EnchantmentSolution#4]
Enchantment Solutions 1.3.3
Spigot version 1.13.2-R0.1
Multiverse core
CMI

anytime I travel to another world my enchants will change on the items I am holding and sometimes wearing.

**Comment by crashtheparty** [comment]
Please send a video/gif of what is happening.

**Comment by DragonisOmega** [comment]
https://www.youtube.com/watch?v=Ff6gJlXn-WU&feature=youtu.be

**Comment by DragonisOmega** [comment]
I was looking this might be a CMI thing so If you can't find any reason for it.  I also posted there too.
Yet when I take off enchantment solutions the problem stops.

**Comment by crashtheparty** [comment]
What is CMI?

**Comment by DragonisOmega** [comment]
I use CMI in place of essentials.

**Comment by DragonisOmega** [comment]
Ok I slowly added in one plugin after another and it turns out the problem is protocollib
https://www.spigotmc.org/resources/protocollib.1997/

Need it for LibsDisguises and another plugin that uses it.  
anyways thank you for taking the time.  I am just glad I found the issue.

**Comment by crashtheparty** [comment]
Finally replicated the issue using a different server. On mob spawning, the plugin changed certain enchantments. This has now been fixed.
