### ISSUE TITLE
Add option to disable anvil decay

### ISSUE THREAD

**Issue by salianifo** [crashtheparty/EnchantmentSolution#41]
I would like an option to disable anvil decay, either as a permission to bypass anvil decay, or a global setting.

**Comment by crashtheparty** [comment]
What does anvil decay mean?

**Comment by salianifo** [comment]
Perhaps anvil damage would have been a better term, but I was referring to how using an anvil has a chance to turn it into a chipped anvil, then damaged anvil, then being completely destroyed.
