### ISSUE TITLE
Enchantments do not change

### ISSUE THREAD

**Issue by 4Cris** [crashtheparty/EnchantmentSolution#42]
After a certain amount of time players always get the same enchantments.

**Comment by grundyboy34** [comment]
Update on this. Here are steps to reproduce.
1) Launch the server
2) Enchant an item or two (observe enchantment pool changes as normal.)
3) Log out of server and log back in
4) Enchant an item (observe enchantment pool doesn't change)

**Comment by grundyboy34** [comment]
Issue is this.
https://github.com/crashtheparty/EnchantmentSolution/blob/7bd67762449806baf4845b08d977f596b1a5e447/src/org/ctp/enchantmentsolution/enchantments/helper/PlayerLevels.java#L200-L207

`if(levels.getPlayer().equals(player))`  
should be modified to
`if (levels.getPlayer().getUniqueId().equals(player.getUniqueId()))`
