### ISSUE TITLE
Smeltery enchant not compatible with CMI durability warnings

### ISSUE THREAD

**Issue by ParadiddlePride** [crashtheparty/EnchantmentSolution#45]
CMI has a warning in the action bar when the durability reaches a certain threshold, such as when an item only has 10% durability left.
We've found that ONLY the Smeltery enchant causes an issue, and disables the Durability warning message. We tested it using pickaxes and axes, but we believe it applies to any tool.

**Comment by crashtheparty** [comment]
Is this still an issue in v2.2.x?

**Comment by ParadiddlePride** [comment]
Yes, we've just tested it on 1.15.1 and it still does not display the warning.
