### ISSUE TITLE
Plugin fails to enable on Paper 1.15.1

### ISSUE THREAD

**Issue by dfsek** [crashtheparty/EnchantmentSolution#46]
When starting the server (PaperSpigot 1.15.1 build 23) the plugin states that the version is not supported, and disables itself.

**Comment by VanillaChan6571** [comment]
Work around found. open the jar with winrar. Drag the .classpath out. Edit with notepad++
Add the version:

`<classpathentry kind="lib" path="D:/Gaming/Minecraft/Plugin Versions/spigot-1.15.1.jar"/>`

save and drag it back into the .jar and it enables.

**Comment by Onyxtite** [comment]
> 
> 
> Work around found. open the jar with winrar. Drag the .classpath out. Edit with notepad++
> Add the version:
> 
> `<classpathentry kind="lib" path="D:/Gaming/Minecraft/Plugin Versions/spigot-1.15.1.jar"/>`
> 
> save and drag it back into the .jar and it enables.

Seemed like a good idea, but my classpath already has that entry.
Could you elaborate please?

**Comment by VanillaChan6571** [comment]
> 
> 
> > Work around found. open the jar with winrar. Drag the .classpath out. Edit with notepad++
> > Add the version:
> > `<classpathentry kind="lib" path="D:/Gaming/Minecraft/Plugin Versions/spigot-1.15.1.jar"/>`
> > save and drag it back into the .jar and it enables.
> 
> Seemed like a good idea, but my classpath already has that entry.
> Could you elaborate please?

Sure, I assume since the dev already has added 1.15 support and not 1.15.1 adding this would just add a check to see if version matches up (for me this did work, it failed to find a class but for some reason still enabled the plugin as it works fine)

At this point I would just use the [2.2.0 Pre-Release 3] since it already supports 1.15.1

**Comment by Onyxtite** [comment]
Thanks for the quick response, i just tried with the dev build and it seems to start up properly :) I guess its a good solution until 2.2 is realeased!
