### ISSUE TITLE
Latest version/update fails to enable on paper-29+ [1.15.1]

### ISSUE THREAD

**Issue by DXUltimate** [crashtheparty/EnchantmentSolution#48]
Pastebin: https://pastebin.com/vnexwcBT

Plugin refuses to load.

**Comment by VanillaChan6571** [comment]
Just get EnchantmentSolution-2.2.0-pre3.jar since it does support 1.15.1 already.

**Comment by DXUltimate** [comment]
Where can I find those versions? =o

EDIT: How does one compile these into their jars in order for them to work?
