### ISSUE TITLE
Telepathy Bugs

### ISSUE THREAD

**Issue by AaronCGaming** [crashtheparty/EnchantmentSolution#5]
Telepathy on a pickaxe currently clears the data of shulker boxes, also seems to be duping blocks like endstone, or stone

**Comment by crashtheparty** [comment]
Unable to reproduce the duplication bug. Please give a list of plugins used to reproduce and under what circumstances. Video of duplication happening would also be helpful.

Telepathy and shulker boxes has been found and fixed,
