### ISSUE TITLE
[2.2.5] Telepathy used on Head blocks dupes them

### ISSUE THREAD

**Issue by DXUltimate** [crashtheparty/EnchantmentSolution#59]
Any item that has telepathy essentially dupes the custom head blocks placed. Please see video on what I mean. Pickaxe has telepathy on it. This works on both 2.2.4 and 2.2.5.

https://youtu.be/iLj9hdQzWDw

It could be because they're named and have different NBT tags on them as well, since this does not work on Wither Skulls. They also strangely enough, do not work on HeadDatabase heads, the ones in video are CMI heads, which is strange.

Thanks for all your hard work on this. =)

**Comment by crashtheparty** [comment]
I'll look into this one soon.

**Comment by crashtheparty** [comment]
Was unable to reproduce; are you able to go on the latest version and try it again?

**Comment by DXUltimate** [comment]
Sure, just downloaded it now with paper 155. Will come back with results
soon. =)

**Comment by DXUltimate** [comment]
This issue seems to have been resolved in paper-155+ and even currently no longer persisting in paper-229. I'll temp close this for now but if it pops up again, I'll reopen it with new evidence.

Thanks again for this.
