### ISSUE TITLE
Unable to find Mending in the End

### ISSUE THREAD

**Issue by razorrider7** [crashtheparty/EnchantmentSolution#6]
My friends and I have been using this on a private SMP server, but we have been unable to find any books or items with mending on them in End Cities. Is there any reason this might be happening? I have not modified the mending enchantment stats, but am using the enchantments_advanced.yml file.

**Comment by crashtheparty** [comment]
The plugin has modified the enchantments and levels showing up on items, so not only is there a different algorithm for getting the enchantments, but there are also even more enchantments for the plugin to go through. I am making a way to increase the likelihood of higher level enchantments in the next release.

**Comment by crashtheparty** [comment]
Never mind, this was an issue. Will be fixed in the next release!

**Comment by razorrider7** [comment]
OK, that is fixed, but now Mending can be found on bows dropped by skeletons, and from other mobs items
