### ISSUE TITLE
 [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to EnchantmentSolution v2.2.9

### ISSUE THREAD

**Issue by benwoo1110** [crashtheparty/EnchantmentSolution#64]
Hi, I have just updated from enchantment solution 2.2.7 to 2.2.9 and I saw this error message from console once players start joining the server. I reverted to version 2.2.7 and I do not face the error anymore. Not very sure what is the issue, could you take a look at it? Thanks!

Server version: PaperSpigot 1.15.2 (build 131)
enchantment solution version: 2.2.9

Here is my log:
[2020-03-12-4.log](https://github.com/crashtheparty/EnchantmentSolution/files/4327637/2020-03-12-4.log)

**Comment by BlackMalakDown** [comment]
I'm actually running into the same exact error from the same update.

**Comment by benwoo1110** [comment]
Hmm ok, so is it safe to run the latest version of enchantment solution?

**Comment by BlackMalakDown** [comment]
I mean I have a reward system plugin that I used to give enchanted books to players that won't load the new enchants, but on weapons and such it seems to still be working.

**Comment by benwoo1110** [comment]
Oh ok, so you have a separate plugin for reward system? The latest version, although still works, is giving a lot of this error causing console spam. Is there a fix for this?

**Comment by BlackMalakDown** [comment]
No idea, creator of the plugin probably already knows. Best best is to hang tight and let him address it. Really no other errors aside from spamming of console

**Comment by benwoo1110** [comment]
ok thanks for helping!
