### ISSUE TITLE
Telepathy on certain SlimeFun4 items dupes them

### ISSUE THREAD

**Issue by dfsek** [crashtheparty/EnchantmentSolution#71]
I am assuming that this is related to, if not the same as, #59. 

When certain SlimeFun4 items are broken with a pickaxe with Telepathy, the item will drop itself, and an identical item with no NBT data.

Examples:

- Teleporter Matrix (from GPS-Based Machines) drops itself and an iron block
- Activator Plates (from GPS-Based Machines) srop themselves and a stone pressure plate.

**Comment by crashtheparty** [comment]
Only way to fix this would be to add compatibility for Slimefun. Even after turning into air, the block still has tile state data that it uses to drop the block.
