### ISSUE TITLE
Issue with Enchantment Solution

### ISSUE THREAD

**Issue by decovee** [crashtheparty/EnchantmentSolution#75]
the plugin is wonderfully good what you did the only problem I have is that despite doing all the steps regarding granting permissions of different levels, both the enchantment table and the functionality of the yunke, this does not work for users of different ranges. The enchantment levels go up in a yunke by combining two elements, and in the enchantment table I get levels that I do not configure in enchantment.yml despite setting the permissions to "true" and giving the permissions to a certain range with enchantmentsolution. " enchantment ".type.level other types of levels appear

**Comment by crashtheparty** [comment]
Please follow the bug report guidelines. I need to see the debug.yml file generated from /esdebug before I can offer help, especially since this is probably just an issue with the configs.
