### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Killborg** [crashtheparty/EnchantmentSolution#76]
Hello, made a quick translation for your plugin. I will add it below, you may use it as you wish.

[ru_ru.zip](https://github.com/crashtheparty/EnchantmentSolution/files/4482972/ru_ru.zip)

**Comment by crashtheparty** [comment]
Looks like the file still has some English in it. 2.3 pre releases should be releasing tonight, which also contains a lot more in the language files. If you can keep the translation updated until 2.3 I will for sure add the translation when it comes out!

**Comment by crashtheparty** [comment]
Are you able to send a new file with updated translation in 2.3? Would love to have more translations!
