### ISSUE TITLE
Enchantment names for use in custom villager trades

### ISSUE THREAD

**Issue by stellaidoscope** [crashtheparty/EnchantmentSolution#77]
Would it be possible to get a list of the enchantment names and how I should put them in custom villager trades so that they either appear on the list or they appear after renaming the item? I tried using the filenames in the config files (hollow_point, enchantmentsolution+hollow_point, etc) or the ones from the /data get entity ("enchantmentsolution:hollow_point") and neither seem to work. Below is a piece of the code I put in for the villager to sell OP tridents: 

> {buy:{id:diamond_block,Count:10},buyB:{id:conduit,Count:5},sell:{id:trident,Count:1,tag:{display:{Name:"\"The Sovereign Sea\"",Lore:["\"The western waters are ours.\""]},Enchantments:[{id:unbreaking,lvl:10},{id:double_strike,lvl:5},{id:loyalty,lvl:3},{id:impaling,lvl:10},**{id:"enchantmentsolution:drowned",lvl:3},{id:"enchantmentsolution:transmutation",lvl:1}**,{id:channeling,lvl:1}]}},maxUses:9999999}

There's another custom enchantment from another plugin (GoldenEnchants) which is double_strike, and it works fine with or without Enchantment Solution. It doesn't appear in the villager's trade at first but it appears after you rename the item; the same can't be said for ES enchantments. Renaming the item does not reveal the drowned or transmutation enchantments, and even through testing they don't activate.

Is there a particular syntax / code I need to add for them to be sold by villagers on items? I'll keep trying to get a random villager to sell me an ES enchanted item; the books they sell give the same data I got that hasn't worked yet.

Thanks!

**Comment by crashtheparty** [comment]
Looks like you did the command fine; the id would be "enchantmentsolution:<enchantment_name>" just as vanilla ones are "minecraft:<enchantment_name>". I just tested (slightly different) code in 1.15 and the enchantment will activate whether or not the name is in the lore. If you don't want it to not appear in the lore, then you can add in the generated lines from /configlore transmutation 1 and /configlore drowned 3 into the first two lines of the lore and you will always see it in the lore and with adding them in the enchantments, it will always work.
