### ISSUE TITLE
Paper Thread Dump returns Magic Guard issue?

### ISSUE THREAD

**Issue by DXUltimate** [crashtheparty/EnchantmentSolution#81]
This is actually more of a question in regards of messages that are being thrown when a server lags. One of the messages that were brought up was this

https://pastebin.com/r66tgXpw

Do you know of anything that would cause a server to lag for about 20 seconds and then spit out this message? This only happens after a server has about 20+ people on, but only a few of them actually has Magic Guard on their shield.

I will provide plugins privately via email or pm if necessary. =)

**Comment by crashtheparty** [comment]
I think I can see why that happens during lag, and I should be able to fix.

**Comment by crashtheparty** [comment]
I don't remember if I looked into this or not for 2.3, if anything happens again like this please let me know.
