### ISSUE TITLE
Anvils no longer repair golden items using ingots

### ISSUE THREAD

**Issue by ParadiddlePride** [crashtheparty/EnchantmentSolution#83]
**Describe the bug**
When using gold_ingot(s) to repair golden tools/gear, the ingot(s) are consumed and the item is not repaired.

**Debug.yml**
https://pastebin.com/kZx4vyMw

**To Reproduce**
1. Obtain a golden item with damage (Ex. golden_sword)
2. Use an anvil with the custom GUI enabled
3. Place golden_ingot(s) into the 2nd slot
4. Click the result in the 3rd slot. The item in the 1st slot will be returned, but the ingots will be gone

**Expected behavior**
When using gold ingots to repair gold items, clicking the 3rd slot in the anvil should return a repaired item. Additionally, it should only consume the required amount of ingots and not a whole stack.

**Comment by crashtheparty** [comment]
This will be fixed in 2.3.0. Not critical, so it will probably wait until then regardless.

Thank you for following the bug report guidelines on this.
