### ISSUE TITLE
Feature Request Height/Width++ Mining up and down

### ISSUE THREAD

**Issue by MidnightSugar** [crashtheparty/EnchantmentSolution#86]
Please add the ability to mine up and down with the length++ and height++ enchantments.

**Comment by crashtheparty** [comment]
What do you mean by mining up/down?

**Comment by MidnightSugar** [comment]
Like the blocks broken should surround the block face mined. You already have it correct for North, West, South, East faces. But the bottom and top faces do not work as they should. It should mine a flat area instead of up and down. Does this make sense? Look up the tinkers construct hammer, because that is what this is imitating.

**Comment by MidnightSugar** [comment]
also maybe you could a third enchantment that does both width and height, maybe called area. So area 1, would do a 3x3 area. Just to simplify things.

**Comment by crashtheparty** [comment]
Not sure why you think the top/bottom faces work as intended since they work exactly as I’ve intended them to work forever. If you can show a diagram explaining what the behavior currently is and what you think the intended result should be, I can take a look.

**Comment by MidnightSugar** [comment]
This is a late response, but after looking at again right now it, I realize my description isn't that clear.

Basically, the shape of the tunnels should change based on which direction you are mining.

Right now, the height++, and width++ enchantments only work when mining sideways. But what if I want to mine up or down? It would not work very well how it is currently set up. (It would go down 2 blocks with height++ enchantment.

How I believe it should work is the ability to mine 3x3 tunnels up and down, based on what face of the block you mined. For example, say you have a pickaxe with height++ and width++ with a level of 1, and mine the block directly under you. You would mine a 3x3 area that only goes 1 block down. And you could keep mining a 3x3 tunnel that goes downward.

If you still don't understand I will draw a diagram.

**Comment by crashtheparty** [comment]
That's exactly what it does though?

**Comment by MidnightSugar** [comment]
Not last I checked. Its possible you could have updated it already or something else was preventing it from working like this. I will check it again.
