### ISSUE TITLE
Issue with Enchantment Solution

### ISSUE THREAD

**Issue by EustassKid93** [crashtheparty/EnchantmentSolution#87]
**Describe the bug**
When i try to add enchant to a book/weapon/armor it costs always 1 level, even if it shows 4/5/15 or anything else

**Debug.yml**
https://pastebin.com/dqQVmDAp

**Screenshots**
![2020-05-11_13 43 43](https://user-images.githubusercontent.com/21223692/81560084-fe586100-9390-11ea-85bc-563423cb0e08.png)
![2020-05-11_13 43 49](https://user-images.githubusercontent.com/21223692/81560086-fef0f780-9390-11ea-8740-2dbac1bad0ba.png)
![2020-05-11_13 46 32](https://user-images.githubusercontent.com/21223692/81560087-ff898e00-9390-11ea-8fef-52d590fa595c.png)
![2020-05-11_13 46 33](https://user-images.githubusercontent.com/21223692/81560088-00222480-9391-11ea-8dc9-fcd1e6afbbdc.png)
![2020-05-11_13 46 37](https://user-images.githubusercontent.com/21223692/81560089-00222480-9391-11ea-8c7b-3dd3c16208f6.png)

**Additional context**
I couldn't find a discord t o ask for support, so im writing here my problem, can you help me to solve this? D:

**Comment by crashtheparty** [comment]
I looked into fixing this in 2.3.0 but apparently forgot to put the code into 2.3, will add for 2.3.1.
