### ISSUE TITLE
Enchantment table GUI - Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by star-kissed** [crashtheparty/EnchantmentSolution#88]
**Describe the bug**
Players can't enchant their items in the enchant table (not able to put any items in).

**Debug.yml**
https://pastebin.com/k7gY2pZf

**To Reproduce**
1. Click on enchant table (opens custom GUI)
2. Shift right-click the item to enchant
3. Nothing happens (no messages in-game)
4. See an error in the console

**Expected behavior**
Item to go in enchant slot

**Screenshots**
Screenshot of the enchantment table GUI
![Screen Shot 2020-05-17 at 9 47 25 PM](https://user-images.githubusercontent.com/61160157/82172675-172caf00-9888-11ea-8495-e9ec38043f07.png)

**Additional context**
Console error messages » https://pastebin.com/heRVxka2

**Comment by crashtheparty** [comment]
Are you using any other person plugins that add more enchantments to Enchantment Solution?

**Comment by star-kissed** [comment]
No. This issue was fixed when using your pre-release version.
