### ISSUE TITLE
Custom mechanic for damage enchantments

### ISSUE THREAD

**Issue by Salty4Daddy** [crashtheparty/EnchantmentSolution#89]
Hello,

Im truly amazed by your plugin. You did a amazing job! Im very grateful for your work and Im hyped for MmoItems support in 2.3.

But I just wanted to ask you...
Do you think it would be possible to rework Sharpness/Thorns/Bane and similars enchantments, which have set the specific ammount of damage, to work more like power?

That means, instead of 0.5 * (level - 1 ) + 1 for sharpness, it would have work like 25% × (level + 1).

Is it possible? Or is it hardcoded? That feature would be amazing for any RPG server, which have mobs having more, than 20HP. 

Thank you for your time and reply! :)

**Comment by crashtheparty** [comment]
It is hardcoded, but that doesn’t mean there can’t be an extra enchantment that can act like that in the future. Don’t want to edit vanilla enchantments for fear that it’ll unintentionally break something.

**Comment by Salty4Daddy** [comment]
New ench like these would be great addition! :)

Wishing you good luck. After I get my pay, I will buy you a pizza. :D
