### ISSUE TITLE
Null Exception error when fishing

### ISSUE THREAD

**Issue by DragonisOmega** [crashtheparty/EnchantmentSolution#92]
**Describe the bug**
https://pastebin.com/nuS92L3R

**Debug.yml**
https://pastebin.com/4ZaKKGNz

**To Reproduce**
Catching a fish while fishing throws the error

**Expected behavior**
not to have it throw an error while fishing.

**Additional context**
I did notice that the error only came up when catching items that were not enchanted.

**Comment by crashtheparty** [comment]
Technically the null pointer exception should be fixed now, but it is still possible for the enchantments to not generate properly on fishing loot. There will be messages in the config about that. If that happens, send in another bug report with the three messages (should end with "Item: <item> Type: <type>") and your debug.yml file.
