### ISSUE TITLE
When you remove enchantment solutions, it's enchantments stay cached somewhere

### ISSUE THREAD

**Issue by blatant-trapdoor** [crashtheparty/EnchantmentSolution#93]
**Describe the bug**
In all of my custom enchantment files, even though enchantment solution is clearly not installed anymore, all the enchantments reappear upon deletion.

**Debug.yml**
No file associated.

**To Reproduce**
1: Uninstall enchantment solution
2: Delete created yml's in other plug-in or custom folders
3: Files reappear

**Expected behavior**
Files not to reappear.

**Screenshots**

**Additional context**
I love the plugin and all, but now I can't remove it from my dev server.

**Comment by blatant-trapdoor** [comment]
I've as well deleted the other plugins and custom folders in order to refresh them, however, the enchantments still return

**Comment by crashtheparty** [comment]
Which version did you have installed before you removed it? Can you also send the startup log?
